import { useTranslation } from "react-i18next";
import AppLangKeys from "../../../../localization/AppLangKeys";

export const ListVisitColumns = (): any => {
    const { t } = useTranslation();

    return [
        {
            name: t(AppLangKeys.medicalrep),
            columnName: "name",
            selector: (row: any) => row.name,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.client_name),
            columnName: "client_name",
            selector: (row: any) => row.client_name,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.specialist_names),
            columnName: "specialist_names",
            selector: (row: any) => row.specialist_names,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.clients_products_names),
            columnName: "clients_products_names",
            selector: (row: any) => row.clients_products_names,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.visitstatues_title),
            columnName: "visitstatues_title",
            selector: (row: any) => row.visitstatues_title,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.visittype_title),
            columnName: "visittype_title",
            selector: (row: any) => row.visittype_title,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.isOffline),
            columnName: "isOffline",
            selector: (row: any) => row.isOffline,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.is_new),
            columnName: "is_new",
            selector: (row: any) => row.is_new,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.village_name),
            columnName: "village_name",
            selector: (row: any) => row.village_name,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.visit_d_diff),
            columnName: "visit_d_diff",
            selector: (row: any) => row.visit_d_diff,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.double_user_name),
            columnName: "double_user_name",
            selector: (row: any) => row.double_user_name,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.trible_user_name),
            columnName: "trible_user_name",
            selector: (row: any) => row.trible_user_name,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.mocLocation),
            columnName: "mocLocation",
            selector: (row: any) => row.mocLocation,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.started_at),
            columnName: "started_at",
            selector: (row: any) => row.started_at,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.created_at),
            columnName: "created_at",
            selector: (row: any) => row.created_at,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.comment),
            columnName: "comment",
            selector: (row: any) => row.comment,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.visit_id),
            columnName: "visit_id",
            selector: (row: any) => row.visit_id,
            sortsortable: false,
            center: true,
            glow: 1,
        },
        {
            name: t(AppLangKeys.client_id),
            columnName: "client_id",
            selector: (row: any) => row.client_id,
            sortsortable: false,
            center: true,
            glow: 1,
        }
    ]
};